# General config options
general:
  # List of worlds where jobs and job quests are disabled. Use world names (case-sensitive).
  worlds-disabled:
    - none

# OPTIONAL: Config options for commands
# If you want to build custom GUIs for UnboundJobs, or want to stick to the non-GUI commands, disable everything below.
commands:
  # OPTIONAL: Config for job list GUI ("/jobs list")
  job-list:
    # OPTIONAL: Enable/disable players bringing up the job list GUI.
    # default: true
    enabled: true

    # OPTIONAL: Enable/disable players joining jobs through the "/jobs list" GUI.
    # default: true
    join-jobs: true

  # OPTIONAL: Config for job profile GUI ("/jobs profile", "/jobs quests", "/jobs news", "/jobs settings")
  job-profile:
    # OPTIONAL: Enable/disable players bringing up the job profile GUI.
    # default: true
    enabled: true

    # OPTIONAL: Enable/disable players viewing the job profile of others using the "/jobs profile <player-name>" command.
    # default: true
    allow-public-profiles: true

# Config options for players
workers:
  # Set a job limit for every player. 0 is not allowed. Set to -1 to disable limit.
  job-limit-per-player: -1

  # Weekly job quest reroll day.
  # Allowed values: sunday, monday, tuesday, wednesday, thursday, friday, saturday
  weekly-quest-reroll-day: sunday

  # OPTIONAL: Default profile visibility. Will only apply to new players.
  # Allowed values: public, private
  # default: private
  default-profile-visiblity: private

# Config options for jobs
jobs:
  # OPTIONAL: List of disabled jobs. Add job names in kebab-case.
  # Useful for when you want to disable jobs without moving/deleting their config files.
  # Uncomment to use.
  disabled-jobs:
    - none

  # Supported values: 1-32767
  max-level: 100

  experience:
    # Enable/disable experience boosts.
    # Active timed boosts will be paused.
    boosts-enabled: true

    # Formula to use for computing experience needed to reach a specific level.
    # Result is rounded because experience is an integer value.
    # Allowed variables:
    # t - target level
    formula: ((t - 1) / 0.5) ^ 1.75

  income:
    # Enable/disable income boosts.
    # Active timed boosts will be paused.
    boosts-enabled: true

    # Formula to use for computing income from tasks.
    # Allowed variables:
    # M - max job level
    # p - base pay
    # j - current job level
    formula: p * ((1 + ((j - 1) / M)) ^ 1.59650776)

